# Generated by Django 5.0.6 on 2026-06-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('breed', models.CharField(max_length=60)),
                ('birth_year', models.IntegerField(default=2021)),
                ('lactation_day', models.IntegerField(default=0)),
                ('herd', models.CharField(default='B', max_length=20)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('risk', 'At risk'), ('critical', 'Critical'), ('estrus', 'In estrus')], max_length=12)),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('confidence', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('vitals', models.JSONField(default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.animal')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_label', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('vet_name', models.CharField(default='Dr. Bello', max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alert')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.animal')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('activity_index', models.FloatField(default=0)),
                ('rumination_min', models.FloatField(default=0)),
                ('body_temp_c', models.FloatField(default=0)),
                ('milk_yield_l', models.FloatField(default=0)),
                ('milk_conductivity', models.FloatField(default=0)),
                ('lying_time_min', models.FloatField(default=0)),
                ('thi', models.FloatField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.animal')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('animal', 'timestamp')},
            },
        ),
    ]
