# Generated by Django 5.0.6 on 2026-06-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='event',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
