# Generated by Django 5.0.6 on 2026-06-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensorreading_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='base_rumination',
            field=models.FloatField(default=6.0),
        ),
    ]
